
```{r}
library(dplyr)
library(readr)
library(ggplot2)
```


## add data

```{r}
VFT <- read.csv("local adaptation/data/processed data/VFT_long_upto2025.csv")
Climvar <- read.csv("local adaptation/data/processed data/Climvar_upto2025.csv")
```
## add annual variables

#### local
```{r}
TP_LA<- Climvar %>%
  group_by(startyear, site) %>%    # for startyear of 2021 for example, months 6-12 were in 2021 and 1-5 were in 2022.
  summarise(T_LA = mean(local_T,na.rm = TRUE),P_LA = mean(local_P,na.rm = TRUE))


VFT$T_LA <- NA
VFT$P_LA <- NA

for (i in 1:nrow(VFT)) {
  site_i = VFT$site[i]
  startyear_i = VFT$startyear[i]
  
  VFT$T_LA [i] <- TP_LA$T_LA[which(TP_LA$site == site_i & TP_LA$startyear== startyear_i) ]
  VFT$P_LA [i] <- TP_LA$P_LA[which(TP_LA$site == site_i & TP_LA$startyear== startyear_i) ]
}

head(VFT)
```

#### regional
```{r}
TP_RA<- Climvar %>%
  group_by(startyear, site) %>%    # for startyear of 2021 for example, months 6-12 were in 2021 and 1-5 were in 2022.
  summarise(T_RA = mean(regional_T,na.rm = TRUE),P_RA = sum(regional_P))


VFT$T_RA <- NA
VFT$P_RA <- NA

for (i in 1:nrow(VFT)) {
  site_i = VFT$site[i]
  startyear_i = VFT$startyear[i]
  
  VFT$T_RA [i] <- TP_RA$T_RA[which(TP_RA$site == site_i & TP_RA$startyear== startyear_i) ]
  VFT$P_RA [i] <- TP_RA$P_RA[which(TP_RA$site == site_i & TP_RA$startyear== startyear_i) ]
}

head(VFT)
```

##add extreme month variables

####local
```{r}
Hottest_month <- 7
Coldest_month <- 1
driest_month <- 12
wettest_month <- 8       ### these values are obtained from Louthan et al., 2022 (https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecm.1528). These were calculated from historical avergaes of precipitation and temperature data.

TP_LM<- Climvar %>%
  group_by(startyear, site, newMonth) %>%    
  summarise(T_LM = mean(local_T,na.rm = TRUE),P_LM = mean(local_P,na.rm = TRUE), 
            T_LMax= max(local_T,na.rm = TRUE), T_LMin= min(local_T,na.rm = TRUE))

VFT$T_LH <- VFT$T_LC <- VFT$T_LW <- VFT$T_LD <- VFT$P_LH <- VFT$P_LW <- VFT$P_LD <- NA

for (i in 1:nrow(VFT)) {
  site_i = VFT$site[i]
  startyear_i = VFT$startyear[i]

  # VFT$T_LH [i] <- ifelse(which(TP_LM$site == site_i & TP_LM$startyear== startyear_i & TP_LM$newMonth==Hottest_month)=0, NA,TP_LM$T_LMax[which(TP_LM$site == site_i & TP_LM$startyear== startyear_i & TP_LM$newMonth==Hottest_month)])
  # VFT$T_LC [i] <- ifelse(length(which(TP_LM$site == site_i & TP_LM$startyear== startyear_i & TP_LM$newMonth==Coldest_month))== 0, NA, TP_LM$T_LMin[which(TP_LM$site == site_i & TP_LM$startyear== startyear_i & TP_LM$newMonth==Coldest_month)])
  VFT$T_LH [i] <- TP_LM$T_LMax[which(TP_LM$site == site_i & TP_LM$startyear== startyear_i & TP_LM$newMonth==Hottest_month)]
  VFT$T_LC [i] <- TP_LM$T_LMin[which(TP_LM$site == site_i & TP_LM$startyear== startyear_i & TP_LM$newMonth==Coldest_month)]
  VFT$T_LW [i] <- TP_LM$T_LM[which(TP_LM$site == site_i & TP_LM$startyear== startyear_i& TP_LM$newMonth==wettest_month) ]
  VFT$T_LD [i] <- TP_LM$T_LM[which(TP_LM$site == site_i & TP_LM$startyear== startyear_i& TP_LM$newMonth==driest_month) ]
  VFT$P_LH [i] <- TP_LM$P_LM[which(TP_LM$site == site_i & TP_LM$startyear== startyear_i& TP_LM$newMonth==Hottest_month) ]
  VFT$P_LW [i] <- TP_LM$P_LM[which(TP_LM$site == site_i & TP_LM$startyear== startyear_i& TP_LM$newMonth==wettest_month) ]
  VFT$P_LD [i] <- TP_LM$P_LM[which(TP_LM$site == site_i & TP_LM$startyear== startyear_i& TP_LM$newMonth==driest_month) ]

}

```

#### regional 

```{r}
TP_RM<- Climvar %>%
  group_by(startyear, site, newMonth) %>%    
  summarise(T_RM = mean(regional_T,na.rm = TRUE),P_RM = sum(regional_P,na.rm = TRUE), 
            T_RMax= max(regional_T,na.rm = TRUE), T_RMin= min(regional_T,na.rm = TRUE))

check <- TP_RM %>%
  dplyr::filter(site == "B1" | site== "B2")

VFT$T_RH <- VFT$T_RC <- VFT$T_RW <- VFT$T_RD <- VFT$P_RH <- VFT$P_RW <- VFT$P_RD <- NA

for (i in 1:nrow(VFT)) {
  site_i = VFT$site[i]
  startyear_i = VFT$startyear[i]

  # VFT$T_RH [i] <- ifelse(which(TP_RM$site == site_i & TP_RM$startyear== startyear_i & TP_RM$newMonth==Hottest_month)=0, NA,TP_RM$T_RMax[which(TP_RM$site == site_i & TP_RM$startyear== startyear_i & TP_RM$newMonth==Hottest_month)])
  # VFT$T_RC [i] <- ifelse(length(which(TP_RM$site == site_i & TP_RM$startyear== startyear_i & TP_RM$newMonth==Coldest_month))== 0, NA, TP_RM$T_RMin[which(TP_RM$site == site_i & TP_RM$startyear== startyear_i & TP_RM$newMonth==Coldest_month)])
  VFT$T_RH [i] <- TP_RM$T_RMax[which(TP_RM$site == site_i & TP_RM$startyear== startyear_i & TP_RM$newMonth==Hottest_month)]
  VFT$T_RC [i] <- TP_RM$T_RMin[which(TP_RM$site == site_i & TP_RM$startyear== startyear_i & TP_RM$newMonth==Coldest_month)]
  VFT$T_RW [i] <- TP_RM$T_RM[which(TP_RM$site == site_i & TP_RM$startyear== startyear_i& TP_RM$newMonth==wettest_month) ]
  VFT$T_RD [i] <- TP_RM$T_RM[which(TP_RM$site == site_i & TP_RM$startyear== startyear_i& TP_RM$newMonth==driest_month) ]
  VFT$P_RH [i] <- TP_RM$P_RM[which(TP_RM$site == site_i & TP_RM$startyear== startyear_i& TP_RM$newMonth==Hottest_month) ]
  VFT$P_RW [i] <- TP_RM$P_RM[which(TP_RM$site == site_i & TP_RM$startyear== startyear_i& TP_RM$newMonth==wettest_month) ]
  VFT$P_RD [i] <- TP_RM$P_RM[which(TP_RM$site == site_i & TP_RM$startyear== startyear_i& TP_RM$newMonth==driest_month) ]

}

```
# scale climate variables

```{r}
VFT$s.T_RA <- NA
VFT$s.T_RA <- scale(VFT$T_RA) 
VFT$s.P_RA <- NA
VFT$s.P_RA <- scale(VFT$P_RA) 
VFT$s.P_RW <- NA
VFT$s.P_RW <- scale(VFT$P_RW) 
VFT$s.P_RD <- NA
VFT$s.P_RD <- scale(VFT$P_RD) 
VFT$s.P_RH <- NA
VFT$s.P_RH <- scale(VFT$P_RH) 
VFT$s.T_RH<- NA
VFT$s.T_RD<- NA
VFT$s.T_RW<- NA
VFT$s.T_RC<- NA
VFT$s.T_RH <- scale(VFT$T_RH) 
VFT$s.T_RC <- scale(VFT$T_RC) 
VFT$s.T_RD <- scale(VFT$T_RD) 
VFT$s.T_RW <- scale(VFT$T_RW) 


VFT$sq.P_RA <- (VFT$P_RA)^2
VFT$sq.T_RA <- (VFT$T_RA)^2
VFT$sq.T_RH <- (VFT$T_RH)^2
VFT$s.sq.T_RH <- scale(VFT$sq.T_RH)
VFT$s.sq.P_RA <- scale(VFT$sq.P_RA)
VFT$s.sq.T_RA <- scale(VFT$sq.T_RA)



VFT$s.T_LA <- NA
VFT$s.T_LA <- scale(VFT$T_LA) 
VFT$s.P_LA <- NA
VFT$s.P_LA <- scale(VFT$P_LA) 
VFT$s.P_LW <- NA
VFT$s.P_LW <- scale(VFT$P_LW) 
VFT$s.P_LD <- NA
VFT$s.P_LD <- scale(VFT$P_LD) 
VFT$s.P_LH <- NA
VFT$s.P_LH <- scale(VFT$P_LH) 
VFT$s.T_LH<- NA
VFT$s.T_LD<- NA
VFT$s.T_LW<- NA
VFT$s.T_LC<- NA
VFT$s.T_LH <- scale(VFT$T_LH) 
VFT$s.T_LC <- scale(VFT$T_LC) 
VFT$s.T_LD <- scale(VFT$T_LD) 
VFT$s.T_LW <- scale(VFT$T_LW) 

VFT$sq.P_LA <- (VFT$P_LA)^2
VFT$sq.T_LA <- (VFT$T_LA)^2
VFT$sq.T_LH <- (VFT$T_LH)^2
VFT$s.sq.T_LH <- scale(VFT$sq.T_LH)
VFT$s.sq.P_LA <- scale(VFT$sq.P_LA)
VFT$s.sq.T_LA <- scale(VFT$sq.T_LA)

```


# add fire metrics
```{r}
library(tidyverse)
library(openxlsx)
library(cropgrowdays)


# load in data
fire_dates_manager <- openxlsx::read.xlsx("Legacy effect/raw-data/VFT fire history/excel fire histories.xlsx", sheet= "manager", startRow=2,detectDates=TRUE)
fire_dates_field_notes <- openxlsx::read.xlsx( "Legacy effect/raw-data/VFT fire history/excel fire histories.xlsx", sheet= "field_notes",startRow=2,detectDates=TRUE)
fire_dates_landsat <- openxlsx::read.xlsx("Legacy effect/raw-data/VFT fire history/excel fire histories.xlsx", sheet= "landsat",startRow=2,detectDates=TRUE)
fire_dates_landscape <- openxlsx::read.xlsx("Legacy effect/raw-data/VFT fire history/excel fire histories.xlsx", sheet= "landscape", startRow=2,detectDates=TRUE)

# reading in the last updated date to make sure you don't accidently say taht a fire was absent, just becuase the dates file hadn't been updated
end_date_manager <- openxlsx::read.xlsx("Legacy effect/raw-data/VFT fire history/excel fire histories.xlsx", sheet= "manager", rows=1,colNames= FALSE) %>% stringr::str_remove("FILE CURRENT AS OF ") %>% as.Date("%m/%d/%y")
end_date_field_notes <- openxlsx::read.xlsx("Legacy effect/raw-data/VFT fire history/excel fire histories.xlsx", sheet= "field_notes", rows=1,colNames= FALSE) %>% stringr::str_remove("FILE CURRENT AS OF ") %>% as.Date("%m/%d/%y")
end_date_landsat <- openxlsx::read.xlsx("Legacy effect/raw-data/VFT fire history/excel fire histories.xlsx", sheet= "landsat", rows=1,colNames= FALSE) %>% stringr::str_remove("FILE CURRENT AS OF ") %>% as.Date("%m/%d/%y")
end_date_landscape <- openxlsx::read.xlsx("Legacy effect/raw-data/VFT fire history/excel fire histories.xlsx", sheet= "landscape", rows=1,colNames= FALSE) %>% stringr::str_remove("FILE CURRENT AS OF ") %>% as.Date("%m/%d/%y")


sites <- c("B1", "B2", "CM", "CH", "IA", "ME", "GSP-LI", "GSP-BI")
record_types <- c("manager", "field_notes", "landsat", "landscape")
June15DOY <- cropgrowdays::day_of_year(as.Date("2020-06-15"))

# fire_histories <- tidyr::expand_grid(record_type = record_types, site = sites, startyear = 1986:2025, TSF = NA, TBF = NA)

## as upto_2026, we're only using the landscape fire records which combine landmanager and landsat

fire_histories <- tidyr::expand_grid(record_type = "landscape", site = sites, startyear = 1986:2025, TSF = NA, TBF = NA)

for (j in 1:3){ 
  if (j== 1) {fire_dates_j <- fire_dates_manager
  end_date <-   end_date_manager}
  if (j== 2) {fire_dates_j <- fire_dates_field_notes
  end_date <-   end_date_field_notes}
  if (j== 3) {fire_dates_j <- fire_dates_landsat
  end_date <-   end_date_landsat}
  
  end_startyear <-  ifelse(cropgrowdays::day_of_year(end_date) <= June15DOY, # if the day of year was before June 15
         as.numeric(format(end_date, "%Y"))-2,  # then the last startyear interval you know TSF for was 2 years before
         as.numeric(format(end_date, "%Y"))-1) # but if not, the last start year was 2 years before
  
  fire_dates_j$fire_startyear <- ifelse(cropgrowdays::day_of_year(fire_dates_j$fire_date) <= June15DOY, # if the day of year was before June 15
                                 as.numeric(format(fire_dates_j$fire_date, "%Y"))-1,  # then return the previous years number, b/c the fire happened over the interaval of previous to current year
                                 as.numeric(format(fire_dates_j$fire_date, "%Y"))) # but if not, then month and day must be greater than 6/15, so  return this years number, because the fire happneed over the interval of current year to the following

for (i in 1:length(sites)){  
  fire_dates_j_i <- fire_dates_j[which(fire_dates_j$site == sites[i]), ]
  first_fire_year <- min(fire_dates_j_i$fire_startyear)
   
#NB that if a fire occurs in startyear 2008, that means that a fire occurred over the 2008-2009 interval. 
  TSF <- NA
  for (ii in first_fire_year:end_startyear){
    if (ii %in% fire_dates_j_i$fire_startyear) {TBF <- TSF # if a fire happens, TSF becomes TBF
    TSF <- 0 # a TSF of zero indicates that a fire burned over the startyear to startyear+ 1 interval
    
    } else {TSF <- TSF +1
    }
    fire_histories$TSF[which(fire_histories$ startyear == ii & fire_histories$site == sites[i]  & fire_histories$ record_type == record_types[j])] <- TSF
    fire_histories$TBF[which(fire_histories$ startyear == ii & fire_histories$site == sites[i]  & fire_histories$ record_type == record_types[j])] <- TBF
  #NB that if a fire occurs in startyear 2008, that means that a fire occurred over the 2008-2009 interval.  
  }

  
}
}

############################################
i=1

for (i in 1:length(sites)){  
  fire_dates_j_i <- fire_dates_landscape[which(fire_dates_landscape$site == sites[i]), ]
  first_fire_year <- min(fire_dates_j_i$startyear)
  
  #NB that if a fire occurs in startyear 2008, that means that a fire occurred over the 2008-2009 interval. 
  TSF <- NA
  end_startyear <- 2025
  for (ii in first_fire_year:end_startyear){
    if (ii %in% fire_dates_j_i$startyear) {TBF <- TSF # if a fire happens, TSF becomes TBF
    TSF <- 0 # a TSF of zero indicates that a fire burned over the startyear to startyear+ 1 interval
    
    } else {TSF <- TSF +1
    }
    fire_histories$TSF[which(fire_histories$ startyear == ii & fire_histories$site == sites[i] )] <- TSF
    fire_histories$TBF[which(fire_histories$ startyear == ii & fire_histories$site == sites[i])] <- TBF
    #NB that if a fire occurs in startyear 2008, that means that a fire occurred over the 2008-2009 interval.  
  }
}

i=1000
for (i in 1:nrow(VFT)) {
    match_TSF <- fire_histories$TSF[fire_histories$site == VFT$site[i] & fire_histories$startyear == VFT$startyear[i]]
    match_TBF <- fire_histories$TBF[fire_histories$site == VFT$site[i] & fire_histories$startyear == VFT$startyear[i]]

    if (length(match_TSF) == 1) {  # Ensure there's exactly one match
      VFT$TSF[i] <- match_TSF}
    
    if (length(match_TBF) == 1) {  # Ensure there's exactly one match
      VFT$TBF[i] <- match_TBF}
}


VFT <- VFT %>%
  select((1:14),  TSF, TBF, everything())
```



# export

```{r}
write.csv(VFT, "local adaptation/data/processed data/VFT_long_upto2025_2.csv")
```





